#+SEQ_TODO: STARTED TODO APPT WAITING(@) DELEGATED(@) DEFERRED(@) SOMEDAY(@) PROJECT | DONE(@) CANCELED(@) NOTE

* به بلندای خیال — شاعر : سعید رضایی

**# به بلندای خیال — **# شاعر : سعید رضایی

در قَفَس می مانم
تا تو پَرواز کنی
تا که پِژواکِ صدایم باشی
در جهانی که صدائی نشنید
*
من اگر در بندم
از صدایِ زنجیر
تو بساز آوازی
واژه هائی از عشق
نغمۀ آزادی
یک ترانه از صُلح
بهرِ هر سرخ و سیاه
یا که هر زرد و سِپید
طَرْحی از پَیوَستَن
دست هائی در هم
نه که مُشتی بر هم
پِلِه هائی از امید
به بلندای خیال
راهی از قَطعِۀ خاک
در گُذَر از افلاک
رو به آن سِرِّ وجود
*
گر به پُشتِ میله ، مانده ام در پیله
تو بشو پروانه
در گُذَر از هر باغ
رنگ و عَطْرَش دریاب
عَطْرها در کِثرَت
همه گلها خوش بو
نقش ها رنگارنگ
همه رنگِ وحدت
رازِ کَثرَت دریاب
راهِ وحدت بِسپار
رازهای این باغ
در دلِ خاک ببین
یک نِگَه بر خورشید
باد و آب و مهتاب
باغبانی پُرکار
در یکی گوشۀ باغ
کِرمِ شب تابی بین
در حِصارِ ناگُزیر
در گُریز از ظُلمت
نورِ خود می تابد
سَهْمِ خود می جوید
*
سَهْمِ تو از دُنیا
یک صدا و آواز
کوششی در پَرواز
دست هائی پُربار
فکر و اندیشۀ ناب
پایمردی در راه
*
و بدان ، در میانِ دیوار
یا که زنجیر و حصار
من تو را می شِنَوَم
دست تو می بینم
ذِهْنِ تو می یابم
و بدانم که تَرَک بردارد
هر حصار و پیله ، صدهزاران میله
و در آغوش کِشیم
روزِ دیدار و وصال
هر چه خوش بختی را
طَعْمِ آزادی را

* زبان خِرَد میگوید

زبان خِرَد میگوید
هر که دارایِ من نباشد دارایِ هیچ نه
از هر چه هست بگذرید و مرا بیابید

منم آفتابِ بینش و دریایِ دانش
پژمردگان را تازه نمایم
و مردگان را زنده کنم
منم آن روشنائی که راهِ دیده بنمایم
و منم شاهبازِ دستِ بینیاز
پرِ بستگان را بگشایم
و پرواز بیاموزم

The Tongue of Wisdom proclaimeth:
He that hath Me not is bereft of all things.
Turn ye away from all that is on earth
  and seek none else but Me.
I am the Sun of Wisdom
  and the Ocean of Knowledge.
I cheer the faint and revive the dead.
I am the guiding Light that illumineth the way.
I am the royal Falcon on the arm of the Almighty.
I unfold the drooping wings of every broken bird
  and start it on its flight.

* درد عشقی کشیده ‌ام که مپرس

درد عشقی کشیده ‌ام که مپرس
زهر هجری چشیده ‌ام که مپرس

گشته ‌ام در جهان و آخر کار
دلبری برگزیده‌ ام که مپرس

آن چنان در هوای خاک درش
می‌رود آب دیده ‌ام که مپرس

من به گوش خود از دهانش دوش
سخنانی شنیده‌ ام که مپرس

سوی من لب چه می‌گزی که مگوی
لب لعلی گزیده ‌ام که مپرس

بی تو در کلبه گدایی خویش
رنج‌هایی کشیده ‌ام که مپرس

همچو حافظ غریب در ره عشق
به مقامی رسیده‌ ام که مپرس

* اگر آنان تير زنند اينان شهد و شير بخشند

اگر آنان تير زنند اينان شهد و شير بخشند
اگر زهر دهند قند بخشند
اگر درد دهند درمان بياموزند
اگر زخم زنند مرهم بنهند
اگر نيش زنند نوش روا دارند

* مثنوى مبارك

مثنوى مبارك

آثار قلم اعلى، ۱۵۹ بديع، جلد ۲، صفحه ۳۰۸ - ۳۲۰

﴿ هوالأبهى ﴾

اى حيات العرش خورشيد وداد
که جهان‌و‌امکان‌چه تونورى نزاد
گر نبودى خلق محجوب از لقا
يک دو حرفى گفتم‌ از سرّ بقا
تا که جانها جمله مرهونت شوند
تا که دلها جمله ‌مجنونت شوند
تا ببينى عالمى مجنون و مست
روحها بهر نثار اندر‌ دو ‌دست
تا رسد امر تو اى فخر زمان
بر فشانند بر قدومت رايگان
سر‌برآر ازکوه جان‌خورشيد وار
تا ببينندت عيان از ‌هر‌کنار
جلوه ده آنروى همچون ماه را
سبز‌و‌‌خرّم کن ز لطف ‌اين‌گاه را
قطره مى‌جويد ز بحرت کوثرى
کوثرى کن ز‌انکه شاه مهترى
ذرّه گشته ملتمس نور تو را
وا ‌دهش‌ از لطف بيچون ‌و چرا
دانه بگشاده دهان سوى سما
تا بيايد بر‌ وى‌‌ از فضلت بها
قطره هاى رحمتت بر وى ببار
اى مليک‌ عرش و اى مير ديار
خرق‌کن‌اين پردهء صد‌‌توى را
خوش تماشا ده کنون‌ آنروى را
زانکه در فضلت نباشد شبهه‌اى
بهر ما بر بند ز لطفت توشه‌اى
مشرق ‌کل‌ کن‌ کنون‌اين‌ غرب را
بهجت مل ده کنون اين شرب را
نور دل را نور ده ز انوار نور
تا ببينند ‌‌از ‌رخت‌ انوار ‌طور
هان بکش آن تيغ اللّهيت را
هين بکش اين‌ دشمنان ‌دينت را
بر فروزان نار‌ ربّانيت را
خوش بسوزان ملحد‌ حربيت را
جمله خفّاشند اى خورشيد روز
سر بر آر‌ و جمله ظلمانى بسوز
صاف‌کن اين درد غم‌آلوده را
نور ده ‌‌اين شمع شب افسرده را
عالمى قائم بتو چون تو‌‌بجان
تا شود پيدا ز امرت ‌کن ‌فکان
اى بهاى جان بياد روى تو
نکته هاگويم همى از خوى تو
تا بر آرم جانها را از خرد
تا ببينم درّ عشقت که خرد
بر فروزم آتشى اندر ‌جهان
تا بسوزم پرده هاى قدسيان
حور معنى را بر‌‌آرم از حجاب
نور غيبى را کنم کشف نقاب
رمزى از اسرار عشق سرمدى
باز گويم چون بجان باز آمدى
خوش‌بيا‌اى‌طير‌‌نارى در بيان
تا نماند وصف هستى در ميان
پاک‌کن اين قلبهاى پر حسد
نقد کن اين قلب‌هاى بى رصد
تا که بيهوشان عهدت اى‌کريم
هم بهوش آيند از جام قديم
بلکه از‌الحان قدس اى يار ما
دورکن هم هوش و بى هوشى زما
اى سرافيل بها اى‌شاه جان
يک حياتى عرضه کن بر ‌مردگان
سدره اوّل بود ‌ز ‌اغصان دل
وا رهانش از هوا و آب و گل
تا‌ز‌جوهر و ز‌عرض فارغ شود
تا ز شمعش شمسها بازغ شود
اين‌نهالت‌غرس‌کن‌در‌ارض‌دل
پس مقدّس دارش از‌‌اشراق و ظل
هم‌تو‌حفظ از‌مختلف‌بادش نما
هم ز وهم مشرک آزادش نما
اصل او ثابت نما در‌ارض‌جان
فرع او را بگذران‌ از آسمان
نو بهارى تو ز نو آور عيان
تا زحشرت بر جهند اين مردگان
جوش‌درياهاى‌عشق‌از‌جوش‌تو
هوش اطيار بقا ‌از هوش تو
بوى پيراهن بوز از مصر جان
سدره موسى نما اينجا عيان
اى نگار از روى توآمد بهار
زين بهار ‌آمد حقايق بيشمار
هرگل‌از‌وى‌دفترى‌ازحسن‌دوست
هر دل از وى کوثرى از فضل هوست
اين‌بهاران را‌خزان نايد ز پى
جمله گلها طائف اندر ‌حول وى
اين‌بهارى‌نه‌که‌جان‌‌‌درکش‌کند
اين بهارى که روانها را کند
آن بهاران شوق خوبان آورد
و اين بهاران‌ عشق يزدان آورد
آن بهاران را فنا باشد عقب
و اين بهاران را بقا باشد لقب
آن‌بهار‌از‌فصل خيزد در‌جهان
و اين بهار از نور روى دلستان
آن بهاران‌‌ لاله ها آرد برون
و اين بهاران ناله ها دارد کنون
اين بهار سرمدى از نور شاه
بر زده خرگاه تا عرش اله
جمله‌در‌خرگاه‌او داخل‌شدند
گر تو چشمت هست بنگر هوشمند
شاه ما چون پرده از رخ بفکند
اين بهاران خيمه بر گردون زند
يار ما چون بفکند از رخ نقاب
اين بهاران بر فروزد بى ‌حجاب
ما برويش در بهاران اندريم
ما ز‌‌رويش در گلستان ننگريم
ما بذکرش فارغيم از ذکر کان
ما ز شمسش بازغيم اندر جهان
گر‌نسيمى‌بر‌وزد زين‌خوش بهار
يوسفان بينى که آيند در نظار
گر نسيمى بر وزد زين بوستان
يوسفان روح بينى در جهان
جسمها‌بينى‌که‌گردد‌همچو روح
روح را هر دم رسد صد گون‌‌فتوح
اين ربيع قدس جانان هر‌دمى
صد بيان دارد ولی کو محرمى
اين بيان باشد ‌مقدّس از لسان
کى بمعنيش رسند اين ناکسان
اين ‌بيان ‌از‌گفت ‌و‌لفظ‌و‌صوت ‌نيست
اين ‌بيان‌جانست و‌اورا موت نيست
عاشقان بينى تو اندر اين بهار
جان نثار آورده هر دم صد هزار
اين بهار عزّ ‌روحانى ‌بود
اين ربيع قدس ربّانى بود
گر وزد بر تو نسيمى زين سبا
جان فانيّت کشد جام بقا
گرنسيمى‌آيدت از‌کوى دوست
جان‌فدايش‌کن‌که‌اينجان‌هم‌از اوست
لالهء توحيد بين‌ در اين بهار
سنبل تجريد بين از زلف يار
غنچه‌هاى‌معرفت‌زين‌طرف‌‌جو
جملگى از شوق او در جستجو
سروهايش حاکى از قدّ نگار
سبزه هايش دفترى از خدّ يار
بلبلانش مست از جام الست
قمريانش از جمال دوست مست
عندليبان در هواى وصل او
جمله مستند از نسيم فضل هو
نغمه اين بلبل ار ظاهر شود
جان خلقان از حسد طاهر شود
بحر‌معنى زين‌بيان موّاج شد
فلک هستى زين کرم لجلاج شد
هر‌شقائق که بر‌آيد ‌زين بهار
صد حقايق بر دمد از سرّ يار
بوى‌مشک‌آيد‌همى از‌جعد‌يار
دست فضلش ميکند بر تو نثار
زلف‌او‌همچون سمندر‌بين بنار
کو همى گردد بنار ‌روى يار
عندليب قدسى از هجران دوست
ناله ها دارد‌که سوزد مغز و پوست
گر زدرد هجر خود آهى کشد
شعله اندر جان خاصان افکند
غير خاصانرا نباشد زين نصيب
وا‌مگير از لطف اين‌فضل اى‌حبيب
بر وزان مشک الهى را زجان
تا ز عطرت بو برند اين‌ناکسان
اين بهار روح باشد جاودان
نى بهارى کز پيش آيد خزان
زين بهار‌قدس روح آيد برون
و ز هوايش نور نوح آيد برون
بر نشاند اهل کشتى را‌بفلک
پس ببخشد هرکه را صد‌گونه ملک
اى جمال اللّه برون‌آ‌از نقاب
تا برون آيد ز مغرب آفتاب
نافهء علم لدنّى بر گشا
مخزن‌ اسرار غيبى بر گشا
تا‌ز‌مشکت بو‌برند‌اين مردگان
تا ز‌خمرت‌خوش شوند‌‌اين بيهشان
اين‌ذلی‌لارض وحدت را ز‌جود
خلعت عزّت ‌بپوشان اى ودود
فانيى را پوش از ثوب بقا
فقر بحتى ‌را چشان شهد غنا
تا برون آيد بکلّى از حجاب
بر ‌درد امکان و هستى را نقاب
بى‌خود‌و سرمست آيد او برون
شمع سان اندر زجاج راجعون
چونکه‌اين‌خار‌از‌گلستانت‌دميد
صد گلستان ‌آر از وى تو پديد
هر گلستان را باسمى زن رقم
پس بهر برگى نما سر‌ّ قدم
تا که انوار رخت آيد عيان
پر کند نورت زمين و آسمان
بر‌وزان‌بادى‌ز‌رحمت ‌اى کريم
بر دران احجاب‌ غفلت زين سقيم
در پناه سدرهء خود جاى ده
روحهاى پاک اى سلطان مه
بابى از رضوان معنى بر گشا
سدّ مکن اين باب از بهر خدا
تا‌درآيم بى حجاب اندر‌جهان
تا کنم‌ رمزى ز احسانت بيان
گفت اللّه اللّه اى مرد نکو
رمز حق در نزد نادانان مگو
اللّه اللّه ‌اى لسان اللّه راز
نرم‌نرمک‌گوى ‌و با مردم بساز
هم‌مگر‌لطف توگيرد دستشان
پس کند فارغ ز بيم اين و آن
پر معنى بر گشا طيّار شو
در هواى قرب او سيار شو
قرب او با‌جان‌نه در‌طى قدم
چون بجان پوئى در آئى در قدم
پس به‌آنى ‌طى افلاک وجود
نيست‌مشکل‌چون‌شوى زاهل سجود
در بيان اين بگويم نکته‌اى
تا برى از آب حيوان حصّه‌اى
تا شوى واقف ز رضوان بقاء
تا برى راهى باقليم لقا
تا بطىّ الارض معنى پى برى
تا چه روح اندر هوايش بر پرى
چون‌تو‌هستى‌اين‌زمان‌در‌دام‌گل
کى برى بوئى تو از رضوان دل
پس برهنه شو تو از ثوب قيود
پس مقدّس کن تو جانرا از حدود
ظلمت دل را ز نورش‌کن‌منير
تا شوى در ملک جانها تو امير
چونکه‌ظلمت‌رفت‌نورش‌مشرق‌است
بر دلت انوار طورش بارق است
چونکه‌ليلت‌رفت‌صبح آمد‌‌پديد
هم نسيم عزّ روحانى وزيد
پس‌تو‌اين‌ظلمات‌و‌اين‌نفس‌تباه
آب حيوانش تجلّى اله
گر‌تو‌زين‌ظلمات نفست‌بگذرى
بى تعب از خمر حيوان بر خورى
پس تو اندر‌ظل‌خضر‌جان‌در آ
تا شوى فارغ از اين ظلمت سرا
آن‌خضر‌نوشيد و‌برهيد از‌ممات
وين خضر‌بخشد دو صد‌عين حيات
آب حيوان بر همه انفاق‌ کرد
خود نموده جان نثار شاه فرد
آن‌خضر‌جهدى نمود آنگه رسيد
زين خضر‌صد چشمه‌آنى شد پديد
آن‌خضر‌‌شد از پى چشمه دوان
وين‌خضر را چشمه ها از پى روان
اى‌بهاى‌جان تو‌باز‌آ زين شکار
تاکنى صيد معانى صد هزار
صيد گورانرا بهل از بهر ‌گور
صيد معنى آر از صحراى طور
صيد‌کردى جان‌عشاقان‌بدشت
تا‌که جانها‌جمله از هستى گذشت
نيست فرصت تا‌تو از‌اسرار گل
پيش بلبل گوئى اى سلطان گل
بر‌پران بازى ز ساعد اى نگار
تا که باز آرد معانى زان ديار
اين‌زمان‌سيمرغ‌معنى‌صيد‌‌کن
بر گشا گنجى تو از مفتاح کن
آنچه‌کردى‌وعده‌اکنون‌کن‌وفا
اى ز نورت روشن اين‌‌ارض و سما
از بهار خود بکن خرّم جهان
تا که رضوانت شود رشک جنان
از حقائق بس شقائق بر‌دمان
در فضاى اين بهارستان جان
پس ز‌هر‌گل رمز‌بلبل‌کن‌عيان
شرح مل در دل بگو با خسروان
زانکه‌اينجا‌اين‌زمان‌نامحرم‌است
محرم‌و‌نامحرم‌‌‌اينجا‌چون‌هم است
اى صباى صبح ‌از زلفين يار
نافه هاى مشک روحانى بيار
اى سحاب فضل روحانى ببار
تا صدف لوءلوء همى آرد ببار
شرح‌ اسرار لَدنّى باز ماند
ذکر طىّ الارض معنى باز ماند
پس تو اى مخمور از‌جام غرور
نار نفست را بدل ميکن بنور
تا‌کنى طى جهان در‌يک نفس
تا رها گردى ز حبس اين قفس
پيش از آن‌که اندرائى‌ظل‌دوست
نى خبر از مغز دارى نى ز پوست
پاى معنيّت بگل باشد فرو
بى خبر ‌ز انوار آن روى نکو
چون‌بظلّ‌شاه‌جان مسکن‌کنى
آن زمان دل از جهانى بر کنى
اول ساعت بدى اندر تراب
آخر ساعت گذشتى ز آفتاب
پس بآنى طى عالم‌هاى جان
بى قدم کردى تو‌اى سالک بدان
اين‌زمان‌بوئى ز‌عطرستان‌جان
بر وزيد و شد معطر اين جهان
باز‌مشک‌جان از‌آن‌رضوان‌جود
بر وزيد و برد جمله آنچه بود
هوش‌و‌بى‌هوشى‌زدست‌اينجا‌برفت
مست و هشيارى همه يکجا برفت
صحو‌شد‌هم‌محو‌و‌محوى‌هم‌نماند
مست شد‌هشيار و‌صحوى هم‌نماند
آنچه‌بود از‌اسم و‌رسم اين‌جهان
فانى آمد چونکه شد شاهم عيان
زانکه اسما‌گر‌دو‌صد‌قرن او پرد
مى نيارد که ز قدرش بو برد
آنچه‌چشمت ديد و‌هم‌گوشت شنيد
او ز جمله پاک آمد اى رشيد
پس‌تو‌با‌اين‌گوش‌وچشم‌اى‌بى‌بصر
کى شوى از ‌سرّ جانان با خبر
چشم ديگر بر گشا از يار نو
گوش ديگر باز کن آنگه شنو
چشم جاهل مى نبيند جز قدم
چشم عارف بيند اسرار قِدم
چشم‌عارف‌صد‌‌هزاران ساله راه
چشم جاهل مى نبيند روى شاه
سائلی مر‌عارفى ‌را گفت کى
تو بر اسرار الهى برده پى
وى‌تو‌از‌خمر‌عنايت گشته مست
هيچ يادت آيد‌‌ از روز الست
گفت‌ياد‌آيد‌مرا‌آن‌صوت وگفت
کو بدى بود و نباشد اين شگفت
هست در گوشم همى آواى او
آن صداى خوب جان افزاى او
عارف ديگر‌‌که بر تر رفته بود
درّ اسرار الهى ‌سفته بود
گفت آن روز خدا آخر نشد
ما در آن يوميم و آن قاصر نشد
يوم اوباقى ‌‌ندارد شب عقب
ما در آن روز و نباشد اين عجب
گر رود ذوقش ز جان روزگار
مى نبينى عرش و فرشى بر قرار
زانکه يوم سرمدى از قدرتش
لا يزول امد پديد از حضرتش
پس‌تو‌اى‌جان‌اين‌معما‌گوش‌دار
پند اسرار الهى هوشدار
تاکه رزق‌جان‌برى‌ازحکمتش
تا که جان سازى فداى طلعتش
تاکه هر دم بشنوى الحان او
تا بنوشى جامى از احسان او
تا شوى واقف تو‌بر‌اسرار‌عشق
تا چشى راح ازل ز انهار عشق
رخ نگردانم‌ز‌سيف اين‌خسان
گر دو‌صد بارم کشند اين کافران
خمر تو نوشيد جانم ز ابتدا
هم بيادت جان دهم ‌در انتها
اى بها يک آتشى از نو فروز
عالم تحقيق و دانش را بسوز
پاک‌کن‌جان‌را‌ا‌ز‌اوصاف‌جهان
بر گشا رمزى ز اسرار نهان
موجى از درياى ژرف معنوى
بر فکن تا فلک لفظى بشکنى
يک قدح در ده که‌تا‌از‌خود رهم
همچو صفدر پرده ها را بر درم
اى زاسمت سدره هستى ببار
هم ز دستت قدرت حق آشکار
اى جهانى در کف تقدير تو
منقلب گه ساکن از تدبير تو
نور ده‌اين‌شمع‌و هم زو نور ده
اين جهات مختلف اى شاه مه
اين چراغى را‌که روشن‌کرده‍ئى
در زجاج حفظ حفظش کردهئى
هم ز دُهن جود داديّش مدد
و ز فتيله امر کرديّش رشد
پس ز باد ظلم حفظش دار تو
تا شود ظاهر از او انوار تو
دست دشمن از سرش کوته نما
اى تو ماه امر و شاه انّما
بنگر اين شمعت که گشته مبتلا
در ميان گِردباد پر بلا
چون ز انوار جمالت نور يافت
پس‌مکن‌در‌نزد امکانش تو مات
چونکه‌کردى‌روشنش‌خامش‌مکن
چونکه‌هوشش‌دادهئى بيهش مکن
اى ز مهرت ذرّه‌خورشيدى شود
وى ز قهرت شير عصفورى بود
بر وزيده بادها‌از هر کنار
مانده ‌اين ‌شمعت ميان اى کردگار
گر تو خواهى آب آتش ميشود
ور نخواهى آتش آندم بفسرد
اى ز‌حکمت ديو گردد همچه حور
وى ز امرت بر دمد از نار نور
گر‌تو‌خواهى‌باد‌چون‌دهنى شود
بر فزايد روح و هم نورى بود
اى بهاء اللّه‌چه نارت‌بر‌فروخت
خرمن هستى عشاقان بسوخت
يک شرر از نار بر دلها زدى
صد هزاران سدره بر سينا زدى
پس ز هر‌دل سدره ها‌ آمد‌ پديد
مو سيا اينجا بسر بايد دويد
تا که نار اللّه معنى را ز جان
بنگريد و وارهيد از قبطيان
اى ذبيح اللّه ز قربانگاه عشق
بر مگرد و جان بده در راه عشق
بى سر و بيجان بيا‌در کوى يار
تا شوى مقبول اهل اين ديار
وادى عشق است روح اللّه بيا
با صليب از راه و هم بيره بيا
از فلک بگذر هم از معراج جسم
اى تو شاه جان و هم بهاج جسم
بلبل روحى تو بر گلزار روح
باز ميآئى تو مهماندار روح
ساعد شه مسکنت اى باز جان
سوى مقصد آى اينجا رايگان
پس تو هم اى نوح‌فلک‌تن‌شکن
خويش را در بحر نورانى فکن
غرق‌کن‌اين‌نفس‌و‌حفظ‌خود‌مخواه
تا برون آرى سر از جيب اله
حفظ‌خواه‌از‌شاه‌و‌از‌کشتى‌مخواه
تا در آئى در پناه حفظ شاه
هم تو اى موسى بطور جان بيا
بگذر از نعل و ردا عريان بيا
تا شوى واقف تو از اسرار نار
ز انکه نار آمد همى از زلف يار
زلف او نارى که سوزد جان عشق
کفر و ايمان‌هم‌سرو سامان عشق
زلف او نارى که بر فاران چمد
هم تبارش گردن دوران خمد
بس کن اى ورقا تو‌‌از‌اسرار‌نار
لؤلؤ جان پيش اين کوران ميار
اين عصا‌سيفى بود‌کز‌دست‌حق
مى بدرد صف امکان چون ورق
آن عصا از دوحهء بستان دميد
و اين عصا از امر حق آمد پديد
آن عصا‌از آب و گل آمد برون
اين عصا از نار دل باشد کنون
اين عصا‌نارى بود کز شعله اش
مى بسوزد پرده هاى غلّ و غش
اين عصا‌بادى بود کز قوم هود
ميشناسد موءمن از کافر جحود
کشتى آمد‌آن‌عصا در عهد نوح
هم عصا‌در‌عهد عيسى گشت روح
موسيا نارت ز جان شعله کشيد
پس بطور جان همى بايد رسيد
نعل چه از جان و از‌ايمان‌گذر
همچو باد از ملک‍جان پرّان گذر
بر‌پر‌از‌فانى‌مکان اى طير‌جان
تا ببزم باقى آن گل رخان
آتش موسى پديد از سدره اش
روح صد عيسى دميد از نفخهاش
نار آن موسى ز طور آمد پديد
نار اين موسى‌ز‌جان شعله کشيد
در ميان کوه جان بس فرقها
هست ظاهر چون ثمر از ورقها
سينه اش سينا‌و نارش نور دوست
کف او بيضا و قلبش طور اوست
اين نه آن‌بيضا‌که‌ز‌امر‌آمد‌پديد
اين همان بيضا که امر آرد پديد
اين زمان فاران‌عشق آمد پديد
يار ما چون پرده از رخ بر دريد
بوى جان ميآيد اين‌دم‌بر‌مشام
مى ندانم کز کجا آيد مدام
اين قدر دانم که از زلفين يار
ميوزد بوئى که جان گردد نثار
نافه مشک الهى باز شد
جان ما با ياد او همراز شد
اى نسيم صبح روحانى بوز
از سباى قدس رحمانى بوز
تا ز بوى عنبرت جانهاى مست
برپرند از ارض‌هستى تا الست
چونکه عنقاى بقا از قاف جان
بر پريد او تا هواى لا مکان
هم بيک پر سير آفاق جهان
کرد از ‌تاييد آن سلطان جان
باز آمد اين زمان از عرش يار
نغمه هاى او برونست از شمار
از گل رويش دى‌آمد‌چون بهار
و ز لب لعلش شب آمد چون نهار
کار عشاقان ز زلفش شد دراز
جمله معشوقان ز هجرش ‌در نياز
گردن گُردان بمويش در کمند
صفدر يزدان ز تيرش مستمند
از لبش جانهاى عشاقان بلب
هم ز وصلش جان‌شاهان در طلب
از جمالش چشم جان معنوى
گشت روشن گر تو نيکو ‌بنگرى
گر نبودى چشم او اندر جهان
چشمه هاى نور کى گشتى روان
از گلش بس گلستان آمد‌پديد
و ز رخش گلهاى معنى بر دميد
نار موسى نور جو در کوى او
جان عيسى روح جو از روى او
گر شبى آيد برون او از‌حجاب
صد جهان روشن کند چون آفتاب
ليل نبود جز ز زلف آن نگار
صبح نايد جز ز نور روى يار
شهرياران جمله ‌اندر شهر عشق
جان نثار آوردهاند از بهر عشق
از‌ جما‌ل ‌او‌ جمال‌‌ا‌لّله‌ پديد
وز لبش دل خمر جان اندر کشيد
جملهء عالم بمويش بسته است
هم ز بهرش سينه هاشان خسته است
چون زليخاى‌جمال آنروى ديد
در مقام دست او دل را بريد
يک‌نفس‌از روح‌خود‌چون‌بر‌دميد
صد هزاران روح عيسى شد پديد
اين‌نه‌وصف او‌بود‌اى‌ذو صفات
وصف آن نورى کزو هستت حيات
گر‌تو‌بر وصف جمالش پى‌برى
از هزاران ‌بحر معنى ‌بگذرى
وصف‌يک‌پرتو‌که باشد اينچنين
وصف او خود چون بود ايمرد دين
چشم عاشق‌چون‌جمال او‌ بديد
هم ز دنيا هم ز عقبى دل بريد
موج درياهاى عشق از موج او
اوج عنقاهاى عشق از اوج او
چونکه‌چشم‌تو‌ز‌چشمش‌نور‌يافت
ظلم باشد گر بغير او ‌بتافت
چونکه نور از‌او‌گرفته‌چشم‌جان
حيف باشد گر فتد بر ديگران
چشم تو از‌چشم‌حق‌گشته عيان
تا نه بينى جز جمالش در جهان
سرّ اين‌سر‌بسته گفتم اى رفيق
درّ اين در خفيه سفتم اى شفيق
تا نيفتد چشم بد بر روى او
تا نيابد غير راه کوى او
همچنين در‌کلّ اعضا‌اين‌بدان
تا رهى از قيد ‌اين ظلماتيان
گوش‌تو‌چون‌نغمهء رازش‌شنيد
رازهاى جانى از سازش شنيد
چونکه صنع ايزدى گشته عيان
چشم بر او کن از اين‌خلق جهان
گر تو‌با‌چشمش‌جهانرا بنگرى
بر هزاران ملک معنى پى برى
مى نبيند چشم او جز روى او
مى نپرد مرغ او جز‌کوى او
از‌وصالش‌جان‌عشاقان بسوخت
و ز‌ فراقش نار دلها بر فروخت
پس بسوزد عاشق بيجان و سر
هم ز هجر و هم ز وصلش اى پسر
پس‌تو‌عشق‌حق‌رفيق‌خود بدان
تا شوى پرّان ز قيد اين جهان
عشق‌آن‌باشدکه‌جان‌فانى‌کنى
جان و دل در ملک باقى افکنى
سرّ اين‌معنى شنو‌گر پى برى
تا به معراج الهى بر پرى
تا‌که نخلت بار روحانى دهد
ميوه هاى قدس نورانى دهد
اى نسيم از‌زلف او عطرى بيار
اى غمام از فضل هو رشحى ببار
تا رياض جان عشاقان او
لاله هاى عشق آرد بس نکو
اين دل عاشق بود عرش ‌اله
چونکه پاک آمد ‌ز قيد ما سواه
چون ز‌حبّش‌بيت او‌‌معمور شد
او به بيت و بيت او مستور شد
بيت او از‌سنگ وگِل‌نبود بدان
بيت‌ او جز ‌دل نباشد اى جوان
چونکه قلبت پاک‌شد از‌نور او
شد مقامش چونکه آمد طور او
چونکه‌بيت اللّه‌عاشق‌شد‌‌‌تمام
جلوه معشوق آمد‌ بر دوام
باز‌عشق‌آمد‌حجاب‌عقل‌سوخت
خرمن‌عرفان و علم و‌فضل سوخت
چونکه‌غيرش‌نيست‌دربيت‌اى‌پسر
جمله حکم او بدان تو سر بسر
پس‌تو‌‌چشم‌و‌گوش‌و‌دست‌از‌‌‌او‌بدان
او ببيند ‌او بگيرد آن زمان
جان‌عارف‌مسجد‌اقصاى اوست
مخزن اسرار او ادناى اوست
چاره‌ئى اکنون ز‌نو بايد نمود
اين نصيحت را بجان بايد شنود
هم ز‌هجر‌و‌وصل هر‌دو در‌گذر
تا رسى در رفرف اصل اى پسر
تا‌تو در‌هجرى يقين در آتشى
هم ز وصلش در تب و هم ناخوشى
پاى نه بر عرصه پاک بقا
که بود غيرش در آن ‌ميدان فنا
گر حديث کان لللّه خوانده‌اى
ور تو رمز ليس ‌غيره ديده‌اى
پاى همت اندرين ره تو گذار
تا شوى فارغ ز وصل و هجر يار
چونکه دانستى يقين ز اسرار
جان که‌نباشد غير‌يزدان در ميان
پس ز‌آب‌جان‌بران‌خاشاک را
تا ببينى جلوه‌ آن پاک را
تا ببينى تو وصال اندر وصال
تا ببينى در دلت نور جمال
اين بود وصلی‌که‌ضد‌‌نبود ورا
بلکه هجرش مى نباشد از ورا
وصل‌و‌هجر‌تو‌بود‌شرک‌اى پسر
گر‌تو ‌دارى گوش بر‌پند پدر
زين دو عقبه چون‌هما‌برپر‌برو
تا هواى ‌وحدت سلطان هو
ليک ترسم ‌که بلغزد پاى تو
وهم بد پيدا شود ‌در راى تو
واجب آمد شرح اين‌معنى‌کنم
بيخ وسواس دل از بُن بر کنم
تا نيفتى زين بيان اندر غرور
وارهى از‌کبر و ناز و شرّ و شور
وصل او را تو تجلّيش بدان
که شده بيچند و‌چون در تو عيان
نور او در تو وديعه او بود
جهد آن کن تا‌که او ظاهر شود
پس‌تو‌وصل‌‌او ز‌خود‌‌جو‌‌اى‌‌نگار
تا نه بينى بعد از اين هجران يار
مخزن کنز الهى هم توئى
ليک از غفلت پى اينان دوى
تا نگردد در ‌تو اوصافش عيان
خويش را در هجر و گمراهى بدان
او ز‌جود‌ خود‌ نکردت‌ بى‌‌نصيب
از صفات و اسم و رسمش اى لبيب
او زلطفش بابها بر تو گشود
تو مبند آن باب ها همچون ‌يهود
چون ‌شنيدى‌‌‌ ناله نى را ‌‌ز‌عشق
اين زمان بشناس او را هم ز عشق
چون‌ شنيدى‌صوت‌نى‌نائى نگر
تا نباشى بى‌خبر از شه مگر
چونکه ‌نائى‌در‌ جهان‌ ‌اغيار ديد
زان سبب نى را حجاب خود گزيد
پس‌تو ‌بر ‌در ‌‌‌اين‌حجابت ‌يکزمان
تا که جز نائى نه بينى در جهان
همچو صفدر بردران احجاب را
تا ببينى جلوه وهّاب را
همچو نى بخروش تو اندر‌ فراق
تا که آيد نائيت اندر وثاق
چون‌در‌آيد‌ نائى ‌دل در‌‌ خروش
سينه هاى عاشقان آيد به جوش
آتشى بفروز زين ‌نى تو همى
تا بسوزى در جهان وصف منى
از منى‌چون ‌ميم‌سوزد در ‌جهان
غير نى باقى نماند در ميان
چونکه ‌گردد ‌چشمت از‌ نورش‌ بصير
غير نائى خود نبينى اى خبير
پس ز‌ نائى بشنو اين اسرارها
تا برى بوئى ‌از اين گلزارها
يک شرر از نار ‌عشقش‌‌ بر‌فروخت
خرمن هستى سلطانى بسوخت
چون‌ جمالش پرده از‌ رخ برکشيد
پرده اجلال سلطانان دريد
خورد ‌چون ‌تيرى ز‌مژگان نگار
بر دريد او صدر جان شهريار
تاج شاهى را ز‌سر‌ آندم فکند
بنده گشت و آنگه ‌افتاد او به بند
همچو‌ ‌صيدى دست ‌‌صيادى‌ ‌فتاد
يا چه کاهى‌ در دم بادى فتاد
گر بود پيکى رود سوى عراق
شرح گويد درد هجران و فراق
کز‌ فراقت‌جان‌ مشتاقان ‌بسوخت
تير هجرت سينهء شاهان بدوخت
در ميان ما و تو اى شهر ‌جان
صد هزاران قاف باشد در ميان
نيست پيکى جز‌که آه پر شرر
يا رود باد صبا گويد خبر
دست از‌ نخلش‌ بسى‌کوتاه‌ ماند
جان ز هجرش بحرها ‌از چشم راند
اى صبا‌ از‌ پيش جانان يکزمان
خوش بران تا کوى آن زورائيان
پس بگويش‌کى‌مدينه کردگار
چون‌بماندى‌چونکه‌رفت از‌برت‌يار
يار تو در حبس و زندان مبتلا
چون حسين اندر زمين کربلا
يک حسين‌ و ‌صد ‌هزارانش يزيد
يک حبيب و اين همه ديو عنيد
چون کليم اندر ميان قبطيان
يا چه روح اللّه ميان سبطيان
همچو يوسف اندر افتاده بچاه
آن چهى که نبودش پايان و راه
بلبلت شد مبتلی اندر قفس
بسته شد هم زين قفس راه نفس

* هو الله

هو الله
ای طالب ملکوت
به الطاف حضرت پروردگار اميدوار باش
و از مَصائِبِ شَديدهِ اين جهان
نااميد مگرد

الحمدلله
خدای مهربان داری
که طَبيبِ هر بيمار است
و غَمخوارِ هر مُبتَلا
پَناهِ يَتيمان است
و مُعين بيکَسان
و بينهايت مِهرِبان

اگر بدانی که قلب عبدالبهاء
چه قَدر مهربان است
البتّه از شِدَّتِ فَرَح و سُرور پَرواز نمائی
و فَريادِ واطوبىٰ به اُوجِ آسمان رِسانی.

والبهاو عَلَیکْ عبدالبهاء عبّاس

* اللّه ابهی


ای متوجّهٔ اِلی اللّه


چشم از جميعِ ماسِوی بَر بَند
و به مَلَکوتِ ابهی بَر گشا


آنچه خواهی از او خواه
و آنچه طلبی از او طلب


به نظری صد هزار حاجاتت روا نمايد
و به التفاتی صد هزار درد بی درمان دوا کند
و به انعطافی زخم‌ها را مَرهم نهد
و به نگاهی دل‌ها را از قيدِ غم برهاند


آنچه کند او کند
ما چه توانيم کرد،
يَفْعُلُ ما يَشاء
و يَحْکُمُ ما يُريد است


پس سَرِ تسليم نـِه
و توکّل بر رَبِّ رحيم بـِه


والبهاء عليک
ع ع

O thou who art turning thy face towards God! Close thine eyes to all things else, and open them to the realm of the All-Glorious. Ask whatsoever thou wishest of Him alone; seek whatsoever thou seekest from Him alone. With a look He granteth a hundred thousand hopes, with a glance He healeth a hundred thousand incurable ills, with a nod He layeth balm on every wound, with a glimpse He freeth the hearts from the shackles of grief. He doeth as He doeth, and what recourse have we? He carrieth out His Will, He ordaineth what He pleaseth. Then better for thee to bow down thy head in submission, and put thy trust in the All-Merciful Lord.

* ای احبّای حقّ

ای احبّای حقّ
از مَفازِۀِ ضَیِّقِۀِ نفس و هویٰ
به فَضاهایِ مُقَدَّسِۀِ اَحَدِیِّه بِشتابید
و در حَدِیقِۀِ تَقدیس و تَنزیه
مَأویٰ گیرید
تا از نَفَحاتِ اَعمالِیِّه

کُلِِّ بَرِیِّه
بشاطیِ عِزِّ اَحَدِیِّه
تَوَجُّه نمایند

O ye the beloved of the one true God!
Pass beyond the narrow retreats of your evil and corrupt desires,
and advance into the vast immensity of the realm of God,
and abide ye in the meads of sanctity and of detachment,
that the fragrance of your deeds may lead the whole of mankind
to the ocean of God’s unfading glory.

* رشح عما

**# رشح عما**

رشح عما		ميريزد			نغمۀ ما
از باد صبا		گشته پديد		جعدۀ ما
شمس طراز		کرده طلوع		وجهۀ ما
بحر صفا			کرده خروش	جذبۀ ما
گنجينۀ حبّ	گشته نهان		درّ وفا

بهجت مل		شد ظاهر		رنّۀ را
نقرۀ ناقوری	جذبۀ لاهوتی	جوّ سما
دور انا هو		کرده بروز		نفخۀ خوش
کوثر حقّ			گشته هويدا	لعل بها
یم خدا			شد کامل		عنّۀ طا

طفح بهائی		لحن خدا
ماهی سرمد	عرش علا
نخلۀ طوبى		لمع صفا
آهنگ عراقی	جذبۀ لا
طلعة لاهوتی	سرّ عما

وجهۀ باقی		کوبۀ ما
آتش موسى		کفّ سنا
نالۀ مستان		صحن لقا
غنچۀ هائی		کلک بها
طفح طهور		عين فنا

* حکایت آورده‌اند

حکایت آورده‌اند
که عارف الهی با عالم نحوی
همراه شدند و همراز گشتند
تا رسیدند بشاطی بحر العظمة

عارف بی ‌تأمّل توسّل فرموده
		بر آب راند
و عالم نحوی — چون نقشِ بر آب محو گشته —
		مبهوت ماند

بانگ زد عارف که چون عنان پیچیدی ؟

گفت
ای برادر چه کنم چون پای رفتنم نیست
سَرْ نَهادن اولیٰ بود

گفت
آنچه از سیبویه و قولویه اَخْذ نموده‌ئی
و یا از مطالب ابن حاجب و ابن مالک حَمْل فرموده‌ئی
بریز و از آب بگذر

  محو میباید نه نحو این را بدان
  گر تو محوی بی‌خطر در آب ران

The story is told of a mystic knower who went on a journey with a learned grammarian for a companion. They came to the shore of the Sea of Grandeur. The knower, putting his trust in God, straightway ﬂung himself into the waves, but the grammarian stood bewildered and lost in thoughts that were as words traced upon the water. The mystic called out to him, “Why dost thou not follow?” The grammarian answered, “O brother, what can I do? As I dare not advance, I must needs go back again.” Then the mystic cried, “Cast aside what thou hast learned from Síbavayh and Qawlavayh, from Ibn-i-Ḥájib and Ibn-i-Málik, and cross the water!”

With renunciation, not with grammar’s rules, one must be armed:
Be nothing, then, and cross this sea unharmed.

* هذا كتابٌ مسطور

هذا كتابٌ مسطور
هذا لوحٌ منشور
قل انّ هذا لهو البيت المعمور
قل انّ هذا لهو الورقة الكافور
قل انّ هذا شجرة الظّهور
قل انّ هذا بحر المسجور
قل انّ هذا ذكرٌ مستور
قل انّ هذا نورٌ فوق كلّ نور

* Hafez

سال‌ها دل طلب جام جم از ما می‌کرد
وان چه خود داشت ز بیگانه تمنا می‌کرد
گوهری کز صدف کون و مکان بیرون است
طلب از گمشدگان لب دریا می‌کرد
مشکل خویش بر پیر مغان بردم دوش
کو به تأیید نظر حل معما می‌کرد
دیدمش خرم و خندان قدح باده به دست
و اندر آن آینه صد گونه تماشا می‌کرد
گفتم این جام جهان بین به تو کی داد حکیم
گفت آن روز که این گنبد مینا می‌کرد
بی دلی در همه احوال خدا با او بود
او نمی‌دیدش و از دور خدا را می‌کرد
این همه شعبده خویش که می‌کرد این جا
سامری پیش عصا و ید بیضا می‌کرد
گفت آن یار کز او گشت سر دار بلند
جرمش این بود که اسرار هویدا می‌کرد
فیض روح القدس ار باز مدد فرماید
دیگران هم بکنند آن چه مسیحا می‌کرد
گفتمش سلسله زلف بتان از پی چیست
گفت حافظ گله‌ای از دل شیدا می‌کرد

* Prayer of `Abdu’l-Bahá

هُو الأَبهَی الأَبهیٰ
ای بی‌نياز
آن مرغان چمن را پرواز ده
و آن بلبلان گلشن را به غزلخوانی دمساز نما
و به آواز ملکوت ابهايت همراز کن.
وجد و طربی در قلوب انداز و جذب و ولهی در افئده و ارواح افکن تا هر يک با چنگ و دف و نی هی‌هی آغاز نمايد و صفت حمد تو گويد تا هيکل عالم به اهتزاز آيد، به هلهله و ولوله آهنگ چنگ الهی را به ملکوت ابهی رساند. ع‌ع

* Quote from Iqan about the seeker

و دَماغِ جان
چون از زُکامِ کَون و امکان
پاک شد
البتّه رائحهٔ جانان را
از مَنازِل بعیده بیابد
و از اثرِ آن رائحه
بمصرِ ایقانِ حضرتِ مَنّان
وارد شود

When the channel of the human soul is cleansed of all worldly and impeding attachments, it will unfailingly perceive the breath of the Beloved across immeasurable distances, and will, led by its perfume, attain and enter the City of Certitude.

* Short Obligatory Prayer

أَشْهَدُ يا إِلهِي
بِأَنَّكَ خَلَقْتَنِيْ
لِعِرْفانِكَ	وَعِبادَتِكَ،
أَشْهَدُ فِي هذا الْحِيْنِ
بِعَجْزِيْ	وَقُوَّتِكَ
وَضَعْفِيْ	وَاقْتِدارِكَ
وَفَقْرِيْ	وَغَنائِكَ،
لا إِلهَ إِلاَّ أَنْتَ المُهَيْمِنُ القَيُّومُ

* Thus with steadfast steps

و به قدمِ یقین
در صِراطِ حقُّ الیقین قَدم گذاریم
که لَعَلَّ نسیمِ رضا
از ریاضِ قبولِ الهی بِوَزَد
و این فانیان را
به ملکوتِ جاودانی رِساند

Thus with steadfast steps
we may tread the Path of certitude,
that perchance the breeze that bloweth
from the meads of the good-pleasure of God
may waft upon us the sweet savours
    of divine acceptance,
and cause us, vanishing mortals that we are,
to attain unto the Kingdom of everlasting glory.

* With what wonders…

O My servants! Could ye apprehend with what wonders of My munificence and
bounty I have willed to entrust your souls, ye would, of a truth, rid
yourselves of attachment to all created things, and would gain a true
knowledge of your own selves—a knowledge which is the same as the
comprehension of Mine own Being. Ye would find yourselves independent of all
else but Me, and would perceive, with your inner and outer eye, and as
manifest as the revelation of My effulgent Name, the seas of My
loving-kindness and bounty moving within you…

مثل شما مثل طیری است که باجنحۀ منیعه در کمال روح و ریحان در هواهای خوش سبحان
با نهایت اطمینان طیران نماید و بعد بگمان دانه بآب و گل ارض میل نماید و بحرص
تمام خود را بآب و تراب بیالاید و بعد که ارادۀ صعود نماید خود را عاجز و مقهور
مشاهده نماید چه که اجنحهٴ آلوده بآب و گل قادر بر طیران نبوده و نخواهد بود در
این وقت آن طایر سماء عالیه خود را ساکن ارض فانیه بیند حال ای عباد پرهای خود را
بطین غفلت و ظنون و تراب غلّ و بغضا میالائید تا از طیران در آسمانهای قدس عرفان
محروم و ممنوع نمانید

* “I myself shall be his ransom”

من طلبنى وجدنى
و من تقدم ّ الى شبراً ّ تقدمت اليه باعاً
و من احبنى احببته
و من احببته قتلته
و من قتلته فعلى ديته
